# Generated by Django 5.1.7 on 2025-03-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
