# Generated by Django 5.1.7 on 2025-03-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posts',
            new_name='postss',
        ),
    ]
